version: "3.9"
services:
  app:
    image: ${IMAGE}
    ports:
      - "80:5001"
    environment:
      PORT: "5001"
      NODE_ENV: "production"
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped